name: Generate sitemap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base_url: https://ayanmemon296.github.io/GTU-Study-Mates/
          output_path: sitemap.xml
